'use strict';
const fs=require('fs'),path=require('path');
const DATA_DIR=path.join(__dirname,'data'),USER_FILE=path.join(DATA_DIR,'users.json');
function ensureUserFile(){if(!fs.existsSync(USER_FILE)){fs.writeFileSync(USER_FILE,JSON.stringify({users:[{id:'u1',name:'Admin User',email:'admin@earth.com',password:'admin123',role:'admin',createdAt:'2024-11-15',status:'active'},{id:'u2',name:'Sarah Chen',email:'sarah@earth.com',password:'user123',role:'user',createdAt:'2025-01-08',status:'active'},{id:'u3',name:'James Rivera',email:'james@earth.com',password:'user123',role:'user',createdAt:'2025-02-20',status:'active'},{id:'u4',name:'Aisha Patel',email:'aisha@earth.com',password:'user123',role:'user',createdAt:'2025-03-05',status:'pending'}]},null,2))}}
ensureUserFile();
function readUsers(){try{return JSON.parse(fs.readFileSync(USER_FILE,'utf8'))}catch{return{users:[]}}}
function writeUsers(d){fs.writeFileSync(USER_FILE,JSON.stringify(d,null,2))}
function makeToken(uid){return Buffer.from(uid+':'+Date.now()).toString('base64')}
function verifyToken(t){try{var d=Buffer.from(t,'base64').toString().split(':');if(Date.now()-parseInt(d[1])>7*24*60*60*1000)return null;return d[0]}catch{return null}}
function userAuth(req,res,next){var a=(req.headers['authorization']||'').replace('Bearer ','');if(!a)return res.status(401).json({error:'Unauthorized'});var uid=verifyToken(a);if(!uid)return res.status(401).json({error:'Token expired'});req.userId=uid;next()}
module.exports=function(app){
app.post('/api/user/register',function(req,res){var n=req.body.name,e=req.body.email,p=req.body.password,r=req.body.role;if(!n||!e||!p)return res.status(400).json({error:'All fields required'});if(p.length<6)return res.status(400).json({error:'Password min 6 chars'});var d=readUsers();if(d.users.find(function(u){return u.email===e.toLowerCase()}))return res.status(409).json({error:'Email exists'});var u={id:'u'+Date.now(),name:n,email:e.toLowerCase(),password:p,role:r||'user',createdAt:new Date().toISOString().split('T')[0],status:'active'};d.users.push(u);writeUsers(d);res.json({token:makeToken(u.id),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/user/login',function(req,res){var e=req.body.email,p=req.body.password;if(!e||!p)return res.status(400).json({error:'Email and password required'});var d=readUsers();var u=d.users.find(function(x){return x.email===e.toLowerCase()&&x.password===p});if(!u)return res.status(401).json({error:'Invalid credentials'});if(u.status==='inactive')return res.status(403).json({error:'Account deactivated'});res.json({token:makeToken(u.id),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/user/profile',userAuth,function(req,res){var d=readUsers();var u=d.users.find(function(x){return x.id===req.userId});if(!u)return res.status(404).json({error:'Not found'});res.json({id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.createdAt,status:u.status})});
app.patch('/api/user/profile',userAuth,function(req,res){var d=readUsers();var i=d.users.findIndex(function(x){return x.id===req.userId});if(i<0)return res.status(404).json({error:'Not found'});if(req.body.name)d.users[i].name=req.body.name;writeUsers(d);res.json({id:d.users[i].id,name:d.users[i].name,email:d.users[i].email,role:d.users[i].role})});
app.get('/api/admin/users',function(req,res,next){var a=(req.headers['authorization']||'').replace('Bearer ','');if(!a)return res.status(401).json({error:'Unauthorized'});next()},function(req,res){var d=readUsers();res.json(d.users.map(function(u){return{id:u.id,name:u.name,email:u.email,role:u.role,createdAt:u.createdAt,status:u.status}}))});
app.patch('/api/admin/users/:id',function(req,res){var d=readUsers();var i=d.users.findIndex(function(x){return x.id===req.params.id});if(i<0)return res.status(404).json({error:'Not found'});if(req.body.name)d.users[i].name=req.body.name;if(req.body.role)d.users[i].role=req.body.role;if(req.body.status)d.users[i].status=req.body.status;writeUsers(d);res.json(d.users[i])});
app.delete('/api/admin/users/:id',function(req,res){var d=readUsers();d.users=d.users.filter(function(x){return x.id!==req.params.id});writeUsers(d);res.json({ok:true})});
};
